### ISSUE TITLE
Error initializing gem

### ISSUE THREAD

**Issue by arjunmenon** [jpmckinney/tf-idf-similarity#27]
```ruby
irb(main):001:0> require 'tf-idf-similarity'
NameError: uninitialized constant TfIdfSimilarity::SimpleDelegator
	from /home/arjun/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/tf-idf-similarity-0.1.5/lib/tf-idf-similarity/token.rb:12:in `<module:TfIdfSimilarity>'
	from /home/arjun/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/tf-idf-similarity-0.1.5/lib/tf-idf-similarity/token.rb:11:in `<top (required)>'
	from /home/arjun/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/arjun/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/arjun/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/tf-idf-similarity-0.1.5/lib/tf-idf-similarity.rb:16:in `<top (required)>'
	from /home/arjun/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /home/arjun/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /home/arjun/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from (irb):1
	from /home/arjun/.rbenv/versions/2.2.3/bin/irb:11:in `<main>'

```

**Comment by arjunmenon** [comment]
The gem hosted in RubyGems does not have `require 'delegate'` in the `token.rb
`
Please push the new version.

**Comment by jpmckinney** [comment]
0.1.6 should be on Rubygems now. Thanks for reporting!

**Comment by arjunmenon** [comment]
If I may ask, how is the normalization of the words carried out, if they are?
Normalized to one or normalized to average length in the document?

**Comment by jpmckinney** [comment]
The words are changed to lowercase and then English possessives and periods are removed: https://github.com/jpmckinney/tf-idf-similarity/blob/master/lib/tf-idf-similarity/token.rb
